nota1 = int(input("digite a primeira nota")) 
peso1 = int(input("digite o primeiro peso")) 

nota2 = int(input("digite a segunda nota")) 
peso2 = int(input("digite o segundo peso")) 

nota3 = int(input("digite a terceira nota")) 
peso3 = int(input("digite o terceiro peso")) 

rtotal = ((nota1 * peso1) + (nota2 * peso2) + (nota3 * peso3))

mediaponderada = rtotal / (peso1 + peso2 + peso3) 
print("tteeste")
print("mediaponderada e:", mediaponderada) 
